# Generated by Django 5.1.4 on 2025-01-27 09:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('category', models.CharField(choices=[('DAILY', '日常费用'), ('TRAVEL', '差旅费用')], default='DAILY', max_length=10, verbose_name='费用分类')),
            ],
            options={
                'verbose_name': '费用类型',
                'verbose_name_plural': '费用类型',
            },
        ),
        migrations.CreateModel(
            name='FundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='正值表示收入，负值表示支出', max_digits=10, verbose_name='金额变动')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='经费变动后的余额', max_digits=10, verbose_name='变动后余额')),
                ('record_type', models.CharField(choices=[('INCOME', '收入'), ('EXPENSE', '支出')], max_length=10, verbose_name='变动类型')),
                ('description', models.TextField(verbose_name='变动说明')),
                ('record_date', models.DateField(default=django.utils.timezone.now, help_text='实际经费变动的日期', verbose_name='变动日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '经费流水',
                'verbose_name_plural': '经费流水',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='发票号码')),
                ('invoice_type', models.CharField(choices=[('DAILY', '日常发票'), ('TRAVEL', '差旅发票')], max_length=10, verbose_name='发票类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('invoice_date', models.DateField(verbose_name='发票日期')),
                ('reimbursement_date', models.DateField(blank=True, null=True, verbose_name='报销日期')),
                ('reimbursement_person', models.CharField(max_length=50, verbose_name='报销人')),
                ('details', models.TextField(blank=True, verbose_name='报销内容明细')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('file', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='发票文件')),
                ('attachment', models.FileField(blank=True, help_text='可上传任意类型的附件文件', null=True, upload_to='attachments/%Y/%m/', verbose_name='附件')),
                ('has_potential_issue', models.BooleanField(default=False, help_text='日常发票金额超过1000且无附件，或差旅发票为汽车交通费且无附件时，标记为可能存在问题', verbose_name='可能存在问题')),
                ('reimbursement_status', models.CharField(choices=[('NOT_SUBMITTED', '未提交'), ('PENDING', '未报销'), ('NOT_TRANSFERRED', '未转入管理员账户'), ('TRANSFERRED', '已转入管理员账户')], default='NOT_SUBMITTED', help_text='发票的报销处理状态', max_length=20, verbose_name='报销状态')),
                ('status_remarks', models.TextField(blank=True, help_text='当状态为"未转入管理员账户"时的说明', verbose_name='状态备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.expensetype', verbose_name='费用类型')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票',
            },
        ),
        migrations.CreateModel(
            name='ReimbursementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reimbursement_date', models.DateField(default=django.utils.timezone.now, verbose_name='报账日期')),
                ('record_type', models.CharField(choices=[('DAILY', '日常报销'), ('TRAVEL', '差旅报销')], max_length=10, verbose_name='报账类型')),
                ('status', models.CharField(choices=[('SUBMITTED', '已提交'), ('COMPLETED', '已报账')], default='SUBMITTED', max_length=10, verbose_name='报账状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('invoices', models.ManyToManyField(to='invoices.invoice', verbose_name='关联发票')),
            ],
            options={
                'verbose_name': '报账记录',
                'verbose_name_plural': '报账记录',
                'ordering': ['-reimbursement_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler', models.CharField(max_length=50, verbose_name='出差人')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('destination', models.CharField(max_length=100, verbose_name='出差地点')),
                ('expense_category', models.CharField(choices=[('TRANSPORT', '交通'), ('ACCOMMODATION', '住宿'), ('OTHER', '其他')], max_length=15, verbose_name='费用类别')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='关联发票')),
            ],
            options={
                'verbose_name': '差旅发票',
                'verbose_name_plural': '差旅发票',
            },
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('TRAIN', '火车'), ('PLANE', '飞机'), ('BUS', '汽车'), ('TAXI', '出租车'), ('OTHER', '其他')], max_length=10, verbose_name='交通类型')),
                ('departure_time', models.DateTimeField(verbose_name='出发时间')),
                ('departure_place', models.CharField(max_length=100, verbose_name='出发地')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('seat_type', models.CharField(choices=[('TRAIN_SECOND', '高铁二等座'), ('TRAIN_FIRST', '高铁一等座'), ('TRAIN_BUSINESS', '商务座'), ('PLANE_ECONOMY', '经济舱'), ('PLANE_BUSINESS', '商务舱'), ('OTHER', '其他')], max_length=15, verbose_name='座位类型')),
                ('travel_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.travelinvoice', verbose_name='差旅发票')),
            ],
            options={
                'verbose_name': '交通明细',
                'verbose_name_plural': '交通明细',
            },
        ),
        migrations.CreateModel(
            name='AccommodationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='入住日期')),
                ('check_out_date', models.DateField(verbose_name='离店日期')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='酒店名称')),
                ('travel_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.travelinvoice', verbose_name='差旅发票')),
            ],
            options={
                'verbose_name': '住宿明细',
                'verbose_name_plural': '住宿明细',
            },
        ),
    ]
