# Generated by Django 5.1.4 on 2025-01-11 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.expensetype', verbose_name='父类型')),
            ],
            options={
                'verbose_name': '费用类型',
                'verbose_name_plural': '费用类型',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='发票号')),
                ('invoice_type', models.CharField(choices=[('DAILY', '日常'), ('TRAVEL', '差旅')], max_length=10, verbose_name='发票类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='发票金额')),
                ('details', models.TextField(verbose_name='发票明细')),
                ('invoice_date', models.DateField(verbose_name='发票日期')),
                ('image', models.ImageField(upload_to='invoice_images/', verbose_name='发票照片')),
                ('reimbursement_person', models.CharField(max_length=50, verbose_name='报销人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.expensetype', verbose_name='费用类型')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票',
            },
        ),
        migrations.CreateModel(
            name='TravelInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler', models.CharField(max_length=50, verbose_name='出差人')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('destination', models.CharField(max_length=100, verbose_name='出差地点')),
                ('expense_category', models.CharField(choices=[('TRANSPORT', '交通'), ('ACCOMMODATION', '住宿'), ('OTHER', '其他')], max_length=15, verbose_name='费用类别')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='关联发票')),
            ],
            options={
                'verbose_name': '差旅发票',
                'verbose_name_plural': '差旅发票',
            },
        ),
        migrations.CreateModel(
            name='TransportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(choices=[('TRAIN', '火车'), ('PLANE', '飞机'), ('BUS', '汽车'), ('TAXI', '出租车'), ('OTHER', '其他')], max_length=10, verbose_name='交通类型')),
                ('departure_time', models.DateTimeField(verbose_name='出发时间')),
                ('departure_place', models.CharField(max_length=100, verbose_name='出发地')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('seat_type', models.CharField(choices=[('TRAIN_SECOND', '高铁二等座'), ('TRAIN_FIRST', '高铁一等座'), ('TRAIN_BUSINESS', '商务座'), ('PLANE_ECONOMY', '经济舱'), ('PLANE_BUSINESS', '商务舱'), ('OTHER', '其他')], max_length=15, verbose_name='座位类型')),
                ('travel_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.travelinvoice', verbose_name='差旅发票')),
            ],
            options={
                'verbose_name': '交通明细',
                'verbose_name_plural': '交通明细',
            },
        ),
        migrations.CreateModel(
            name='AccommodationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='入住日期')),
                ('check_out_date', models.DateField(verbose_name='离店日期')),
                ('hotel_name', models.CharField(max_length=100, verbose_name='酒店名称')),
                ('travel_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.travelinvoice', verbose_name='差旅发票')),
            ],
            options={
                'verbose_name': '住宿明细',
                'verbose_name_plural': '住宿明细',
            },
        ),
    ]
