# Generated by Django 5.1.4 on 2025-01-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='details',
            field=models.TextField(blank=True, verbose_name='报销内容明细'),
        ),
    ]
