# Generated by Django 5.1.4 on 2025-01-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_invoice_remarks_alter_invoice_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensetype",
            name="category",
            field=models.CharField(
                choices=[("DAILY", "日常费用"), ("TRAVEL", "差旅费用"), ("BOTH", "通用")],
                default="BOTH",
                max_length=10,
                verbose_name="费用分类",
            ),
        ),
    ]
