# Generated by Django 5.1.4 on 2025-01-12 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_add_travel_expense_types"),
        ("invoices", "0003_expensetype_category"),
    ]

    operations = []
