# Generated by Django 5.1.4 on 2025-01-12 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_merge_20250112_1032"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="image",
        ),
        migrations.AddField(
            model_name="invoice",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="invoices/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="发票文件",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="金额"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=50, unique=True, verbose_name="发票号码"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("DAILY", "日常发票"), ("TRAVEL", "差旅发票")],
                max_length=10,
                verbose_name="发票类型",
            ),
        ),
    ]
