# Generated by Django 5.1.4 on 2025-01-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0005_remove_invoice_image_invoice_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expensetype",
            name="category",
            field=models.CharField(
                choices=[("DAILY", "日常费用"), ("TRAVEL", "差旅费用")],
                default="DAILY",
                max_length=10,
                verbose_name="费用分类",
            ),
        ),
    ]
