# Generated by Django 5.1.4 on 2025-01-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0006_alter_expensetype_category"),
        ("invoices", "0007_create_initial_expense_types"),
    ]

    operations = []
