# Generated by Django 5.1.4 on 2025-01-13 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0008_merge_20250113_1231"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensetype",
            name="parent",
        ),
    ]
