# Generated by Django 5.1.4 on 2025-01-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0009_remove_expensetype_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="可上传任意类型的附件文件",
                null=True,
                upload_to="attachments/%Y/%m/",
                verbose_name="附件",
            ),
        ),
    ]
