# Generated by Django 5.1.4 on 2025-01-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0010_invoice_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="has_potential_issue",
            field=models.BooleanField(
                default=False,
                help_text="日常发票金额超过1000且无附件，或差旅发票为汽车交通费且无附件时，标记为可能存在问题",
                verbose_name="可能存在问题",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reimbursement_status",
            field=models.CharField(
                choices=[
                    ("NOT_SUBMITTED", "未提交"),
                    ("PENDING", "未报销"),
                    ("NOT_TRANSFERRED", "未转入管理员账户"),
                    ("TRANSFERRED", "已转入管理员账户"),
                ],
                default="NOT_SUBMITTED",
                help_text="发票的报销处理状态",
                max_length=20,
                verbose_name="报销状态",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="status_remarks",
            field=models.TextField(
                blank=True, help_text='当状态为"未转入管理员账户"时的说明', verbose_name="状态备注"
            ),
        ),
    ]
