# Generated by Django 5.1.4 on 2025-01-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0011_invoice_has_potential_issue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FundRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="正值表示收入，负值表示支出",
                        max_digits=10,
                        verbose_name="金额变动",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[("INCOME", "收入"), ("EXPENSE", "支出")],
                        max_length=10,
                        verbose_name="变动类型",
                    ),
                ),
                ("description", models.TextField(verbose_name="变动说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="记录时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "经费流水",
                "verbose_name_plural": "经费流水",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReimbursementRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reimbursement_date", models.DateTimeField(verbose_name="报账时间")),
                (
                    "record_type",
                    models.CharField(
                        choices=[("DAILY", "日常报销"), ("TRAVEL", "差旅报销")],
                        max_length=10,
                        verbose_name="报账类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUBMITTED", "已提交"), ("COMPLETED", "已报账")],
                        default="SUBMITTED",
                        max_length=10,
                        verbose_name="报账状态",
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "invoices",
                    models.ManyToManyField(to="invoices.invoice", verbose_name="关联发票"),
                ),
            ],
            options={
                "verbose_name": "报账记录",
                "verbose_name_plural": "报账记录",
                "ordering": ["-reimbursement_date"],
            },
        ),
    ]
