# Generated by Django 5.1.4 on 2025-01-13 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0012_fundrecord_reimbursementrecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundrecord",
            options={
                "ordering": ["-record_date", "-created_at"],
                "verbose_name": "经费流水",
                "verbose_name_plural": "经费流水",
            },
        ),
        migrations.AddField(
            model_name="fundrecord",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="经费变动后的余额",
                max_digits=10,
                verbose_name="变动后余额",
            ),
        ),
        migrations.AddField(
            model_name="fundrecord",
            name="record_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="实际经费变动的日期",
                verbose_name="变动日期",
            ),
        ),
    ]
