# Generated by Django 5.1.4 on 2025-01-14 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0013_alter_fundrecord_options_fundrecord_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reimbursementrecord",
            name="reimbursement_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="报账日期"
            ),
        ),
    ]
