# Generated by Django 5.1.4 on 2025-01-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0014_alter_reimbursementrecord_reimbursement_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="reimbursement_date",
            field=models.DateField(blank=True, null=True, verbose_name="报销日期"),
        ),
        migrations.AddField(
            model_name="reimbursementrecord",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="总金额"
            ),
        ),
    ]
