from django.urls import path
from . import views

app_name = 'invoices'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # 管理功能的URL
    path('manage/', views.manage_dashboard, name='manage_dashboard'),
    path('manage/login/', views.manage_login, name='manage_login'),
    path('manage/logout/', views.manage_logout, name='manage_logout'),
    # 添加数据 API 路由到发票相关路由之前
    path('manage/invoices/data/', views.manage_invoice_list_data, name='manage_invoice_list_data'),
    path('manage/invoices/', views.manage_invoice_list, name='manage_invoice_list'),
    path('manage/invoices/add/', views.manage_invoice_add, name='manage_invoice_add'),
    path('manage/invoices/<int:pk>/edit/', views.manage_invoice_edit, name='manage_invoice_edit'),
    path('manage/invoices/<int:pk>/delete/', views.manage_invoice_delete, name='manage_invoice_delete'),
    path('manage/expense-types/', views.manage_expense_type_list, name='manage_expense_type_list'),
    path('manage/expense-types/add/', views.manage_expense_type_add, name='manage_expense_type_add'),
    path('manage/expense-types/<int:pk>/edit/', views.manage_expense_type_edit, name='manage_expense_type_edit'),
    path('manage/expense-types/<int:pk>/delete/', views.manage_expense_type_delete, name='manage_expense_type_delete'),
    path('manage/stats/personal/', views.manage_personal_stats, name='manage_personal_stats'),
    path('manage/stats/expense-type/', views.manage_expense_type_stats, name='manage_expense_type_stats'),
    path('manage/invoice/<int:pk>/detail/', views.manage_invoice_detail, name='manage_invoice_detail'),
    path('manage/invoices/batch-delete/', views.manage_invoice_batch_delete, name='manage_invoice_batch_delete'),
    path('manage/parse-invoice/', views.parse_invoice, name='parse_invoice'),
    path('manage/reimbursement/', views.manage_reimbursement_list, 
         name='manage_reimbursement_list'),
    path('manage/reimbursement/add/', views.manage_reimbursement_add,
         name='manage_reimbursement_add'),
    path('manage/reimbursement/<int:pk>/', views.manage_reimbursement_detail,
         name='manage_reimbursement_detail'),
    path('manage/reimbursement/<int:pk>/add-invoice/', views.manage_reimbursement_add_invoice,
         name='manage_reimbursement_add_invoice'),
    path('manage/reimbursement/<int:pk>/remove-invoice/<int:invoice_pk>/', 
         views.manage_reimbursement_remove_invoice,
         name='manage_reimbursement_remove_invoice'),
    path('manage/reimbursement/<int:pk>/batch-remove-invoices/', 
         views.manage_reimbursement_batch_remove_invoices,
         name='manage_reimbursement_batch_remove_invoices'),
    path('manage/reimbursement/<int:pk>/delete/', views.manage_reimbursement_delete,
         name='manage_reimbursement_delete'),
    path('manage/reimbursement/<int:pk>/complete/', views.manage_reimbursement_complete,
         name='manage_reimbursement_complete'),
    path('manage/reimbursement/unreimbursed-invoices/', views.manage_unreimbursed_invoices,
         name='manage_unreimbursed_invoices'),
    path('manage/fund/', views.manage_fund_list, name='manage_fund_list'),
    path('manage/fund/add/', views.manage_fund_add, name='manage_fund_add'),
    path('manage/fund/<int:pk>/edit/', views.manage_fund_edit, name='manage_fund_edit'),
    path('manage/fund/<int:pk>/delete/', views.manage_fund_delete, name='manage_fund_delete'),
    path('manage/reimbursement/data/', views.manage_reimbursement_list_data, name='manage_reimbursement_list_data'),
    path('manage/fund/data/', views.manage_fund_list_data, name='manage_fund_list_data'),
] 